name: Update EPG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update EPG
        run: /EPG/epg.sh

      - name: setup git config
        run: |
          git config user.name "Github Action"
          git config user.email "action@github.com"

      - name: commit
        run: |
          git pull
          cd EPG && git add .
          git commit -m "Update EPG" || echo "No changes to commit"
          git push origin main  # Ajustez si nécessaire
